# docker-compose.yml
version: '3.8'
services:
  minecraft-agent:
    image: ${DOCKER_IMAGE}
    container_name: ${APP_NAME}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /opt/mscs:/opt/mscs
      - /usr/local/bin/mscs:/usr/local/bin/mscs
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - SERVER_PROPERTIES_PATH=${SERVER_PROPERTIES_PATH}
      - MINECRAFT_MSCS_PATH=${MINECRAFT_MSCS_PATH}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  web:
    external: true